apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-k8s-backend-deployment
  labels:
    app: yolo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: yolo_client
          image: pkoriris/yolo_app:v1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 5050
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
          volumeMounts:
            - name: backend-storage
              mountPath: /app/data
      volumes:
        - name: backend-storage
          emptyDir: {}
