apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
data:
  MONGO_INITDB_ROOT_USERNAME: TW9uZ291c2Vy
  MONGO_INITDB_ROOT_PASSWORD: TW9uZ291c2Vy
  MONGO_URI: bW9uZ29kYjovL21vbmdvLXNlcnZpY2U6MjcwMTcvWU9MTz9hdXRoU291cmNlPXdyaXRlYXBwJnc9MQ==

